version: '3.8'

services:
  fastapi:
    build: .
    container_name: miniapp-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend # we do not need to build each time


  telegram-bot:
    build: .
    container_name: telegram-bot
    command: python backend/telegram_bot.py
    depends_on:
      - fastapi
    volumes:
      - .:/app
    env_file:
      - .env



  db:
    image: postgres:15
    container_name: miniapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: miniapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
